name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    branches: [ "master" ]

jobs:
  
  analyze:
    name: Analyze vulnerabilities
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
    - name: Autobuild
      uses: github/codeql-action/autobuild@v2
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

  build:
    runs-on: ubuntu-latest
    needs: analyze
    steps:
    - uses: actions/checkout@v3
    - name: Build artifacts
      run: make
    - name: list files
      run: ls -la
  
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/upload-artifact@v3
      with:
        name: ri36
        path: ./ri36
