name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      - name: Build artifacts
        run: make
  upload:
    needs: build
    - uses: actions/upload-artifact@v3
      with:
        name: ri36
        path: ri36
